/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthForumsSlugIndexRouteImport } from './routes/_auth/forums/$slug/index'
import { Route as AuthForumsSlugPostNumberIndexRouteImport } from './routes/_auth/forums/$slug/$postNumber/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForumsSlugIndexRoute = AuthForumsSlugIndexRouteImport.update({
  id: '/forums/$slug/',
  path: '/forums/$slug/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForumsSlugPostNumberIndexRoute =
  AuthForumsSlugPostNumberIndexRouteImport.update({
    id: '/forums/$slug/$postNumber/',
    path: '/forums/$slug/$postNumber/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/forums/$slug': typeof AuthForumsSlugIndexRoute
  '/forums/$slug/$postNumber': typeof AuthForumsSlugPostNumberIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/forums/$slug': typeof AuthForumsSlugIndexRoute
  '/forums/$slug/$postNumber': typeof AuthForumsSlugPostNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/forums/$slug/': typeof AuthForumsSlugIndexRoute
  '/_auth/forums/$slug/$postNumber/': typeof AuthForumsSlugPostNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/forums/$slug' | '/forums/$slug/$postNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/forums/$slug' | '/forums/$slug/$postNumber'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/forums/$slug/'
    | '/_auth/forums/$slug/$postNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forums/$slug/': {
      id: '/_auth/forums/$slug/'
      path: '/forums/$slug'
      fullPath: '/forums/$slug'
      preLoaderRoute: typeof AuthForumsSlugIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forums/$slug/$postNumber/': {
      id: '/_auth/forums/$slug/$postNumber/'
      path: '/forums/$slug/$postNumber'
      fullPath: '/forums/$slug/$postNumber'
      preLoaderRoute: typeof AuthForumsSlugPostNumberIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthForumsSlugIndexRoute: typeof AuthForumsSlugIndexRoute
  AuthForumsSlugPostNumberIndexRoute: typeof AuthForumsSlugPostNumberIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthForumsSlugIndexRoute: AuthForumsSlugIndexRoute,
  AuthForumsSlugPostNumberIndexRoute: AuthForumsSlugPostNumberIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
